[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Tony Gao", email = "tonyzgao@gmail.com"},
]
dependencies = [
    "ipykernel>=6.26.0",
    "numpy>=1.26.1",
]
requires-python = ">=3.12,<3.13"
readme = "README.md"
license = {text = "MIT"}

